[database]
path = "../数据库.db"

[cookies]
SCF = "Al27QcfLyB-nrUrbxBTYCZej24Wx1VR7Fx7p2Cm3SpTnAVbOdSnLw7iO5oRo88vjtEAM0oxpiRG5K82HbiM5ecg."
SUB = "_2A25K9LIPDeRhGeBM4lUY8C3OyjWIHXVpiEvHrDV8PUNbmtAYLWbbkW9NRL8DEn-OjE3jZMAdvfG3wFVMgpWFjNHz"
SUBP = "0033WrSXqPxfM725Ws9jqgMF55529P9D9WWBpRIpqPgjMXI3lyEST_o.5JpX5KzhUgL.FoqE1KM4eheEeK.2dJLoI7yzqPSXUPiyM7tt"
ALF = "02_1746423647"
SINAGLOBAL = ""
_s_tentry = ""
Apache = ""
ULV = ""
XSRF-TOKEN = ""
PC_TOKEN = ""
WBPSESS = ""
ALC = "ALC-6Sdmkb-1743831647-6-548233898-14da5bf7491e494def89f9db2487-2"
X-CSRF-TOKEN = "CK-Yco0oN7CYcae-JVeocaIYNWF-CXOtgo1YpXGzx_vaCXF-xHg="

[cookies_info]
update_time = "2025-04-05 13:40:46"
